#!/usr/bin/env Rscript

# ============================================================
# PERSONAL R LIBRARY
# ============================================================

user_library <- "/users/a/r/arslank/Rlibs"

.libPaths(
  unique(
    c(
      user_library,
      .libPaths()
    )
  )
)

suppressPackageStartupMessages({
  library(tidyverse)
  library(glue)
  library(grid)
})

# ============================================================
# UV-CPD WT / CSB / DDB2 / XPC VIOLIN PLOTS
#
# Input:
#
#   UVCPD_FINAL_common_genes_replicate_mean.tsv
#
# Expected genotypes:
#
#   WT
#   CSB
#   DDB2
#   XPC
#
# Plot organization:
#
#   X-axis: Q0, Q1, Q2, Q3, Q4
#   Y-axis: replicate-mean gene-level log2(TS/NTS)
#   Rows: 0.5h, 2h, 4h, 8h
#   Columns: WT, CSB, DDB2, XPC
#
# Each gene contributes one value after averaging its
# independently calculated R1 and R2 log2(TS/NTS) values.
# ============================================================

# ============================================================
# CONFIGURATION
# ============================================================

base_dir <- "/work/users/a/r/arslank"

# This directory must contain the XPC-inclusive replicate-mean
# table generated by the upstream allTS/allNTS analysis.
analysis_dir <- file.path(
  base_dir,
  "TCR_UVCPD_WT_CSB_DDB2_XPC_allTS_allNTS_quartiles"
)

input_file <- file.path(
  analysis_dir,
  "UVCPD_FINAL_common_genes_replicate_mean.tsv"
)

outdir <- file.path(
  analysis_dir,
  "violin_plots"
)

dir.create(
  outdir,
  showWarnings = FALSE,
  recursive = TRUE
)

if (!file.exists(input_file)) {
  stop(
    "\nInput table does not exist:\n  ",
    input_file,
    "\n\nThe upstream allTS/allNTS analysis must first be run ",
    "with WT, CSB, DDB2, and XPC samples."
  )
}

# ============================================================
# FACTOR ORDERS
# ============================================================

genotype_order <- c(
  "WT",
  "CSB",
  "DDB2",
  "XPC"
)

time_order <- c(
  "0.5h",
  "2h",
  "4h",
  "8h"
)

quartile_order <- c(
  "Q0",
  "Q1",
  "Q2",
  "Q3",
  "Q4"
)

# Violin kernel-density smoothing.
density_adjust <- 1.0

# Add this proportion beyond the most extreme observed value.
axis_padding_fraction <- 0.10

# ============================================================
# TIMEPOINT COLORS
# ============================================================

time_colors <- c(
  "0.5h" = "#F4A6A6",
  "2h"   = "#E35D5D",
  "4h"   = "#C62828",
  "8h"   = "#7F0000"
)

# ============================================================
# READ INPUT TABLE
# ============================================================

message(
  "\nReading:\n  ",
  input_file
)

gene_ratios_mean_raw <- read_tsv(
  input_file,
  show_col_types = FALSE,
  progress = FALSE
)

required_columns <- c(
  "genotype",
  "timepoint",
  "quartile",
  "gene_match_id",
  "mean_log2_TS_over_NTS"
)

missing_columns <- setdiff(
  required_columns,
  names(
    gene_ratios_mean_raw
  )
)

if (length(missing_columns) > 0) {
  stop(
    "\nInput table is missing required columns:\n  ",
    paste(
      missing_columns,
      collapse = ", "
    )
  )
}

# ============================================================
# VERIFY ALL FOUR GENOTYPES ARE PRESENT
# ============================================================

observed_genotypes <- gene_ratios_mean_raw %>%
  transmute(
    genotype = as.character(
      genotype
    )
  ) %>%
  filter(
    !is.na(genotype),
    genotype != ""
  ) %>%
  distinct(
    genotype
  ) %>%
  pull(
    genotype
  )

missing_genotypes <- setdiff(
  genotype_order,
  observed_genotypes
)

unexpected_genotypes <- setdiff(
  observed_genotypes,
  genotype_order
)

message(
  "\nObserved genotypes: ",
  paste(
    observed_genotypes,
    collapse = ", "
  )
)

if (length(unexpected_genotypes) > 0) {
  message(
    "Ignoring unexpected genotypes: ",
    paste(
      unexpected_genotypes,
      collapse = ", "
    )
  )
}

if (length(missing_genotypes) > 0) {
  stop(
    "\nThe input table does not contain all required genotypes.\n",
    "Missing:\n  ",
    paste(
      missing_genotypes,
      collapse = ", "
    ),
    "\n\nAdding XPC to genotype_order alone is not sufficient. ",
    "The upstream allTS/allNTS analysis must include XPC samples."
  )
}

# ============================================================
# PREPARE PLOT DATA
# ============================================================

violin_plot_data <- gene_ratios_mean_raw %>%
  filter(
    as.character(genotype) %in%
      genotype_order
  ) %>%
  transmute(
    genotype = factor(
      as.character(genotype),
      levels = genotype_order
    ),

    timepoint = factor(
      as.character(timepoint),
      levels = time_order
    ),

    quartile = factor(
      as.character(quartile),
      levels = quartile_order
    ),

    gene_match_id = as.character(
      gene_match_id
    ),

    gene_id = if (
      "gene_id" %in%
        names(gene_ratios_mean_raw)
    ) {
      as.character(
        gene_ratios_mean_raw$gene_id
      )
    } else {
      NA_character_
    },

    gene_name = if (
      "gene_name" %in%
        names(gene_ratios_mean_raw)
    ) {
      as.character(
        gene_ratios_mean_raw$gene_name
      )
    } else {
      NA_character_
    },

    R1_TS_count = if (
      "R1_TS_count" %in%
        names(gene_ratios_mean_raw)
    ) {
      suppressWarnings(
        as.numeric(
          gene_ratios_mean_raw$R1_TS_count
        )
      )
    } else {
      NA_real_
    },

    R1_NTS_count = if (
      "R1_NTS_count" %in%
        names(gene_ratios_mean_raw)
    ) {
      suppressWarnings(
        as.numeric(
          gene_ratios_mean_raw$R1_NTS_count
        )
      )
    } else {
      NA_real_
    },

    R2_TS_count = if (
      "R2_TS_count" %in%
        names(gene_ratios_mean_raw)
    ) {
      suppressWarnings(
        as.numeric(
          gene_ratios_mean_raw$R2_TS_count
        )
      )
    } else {
      NA_real_
    },

    R2_NTS_count = if (
      "R2_NTS_count" %in%
        names(gene_ratios_mean_raw)
    ) {
      suppressWarnings(
        as.numeric(
          gene_ratios_mean_raw$R2_NTS_count
        )
      )
    } else {
      NA_real_
    },

    R1_log2_TS_over_NTS = if (
      "R1_log2_TS_over_NTS" %in%
        names(gene_ratios_mean_raw)
    ) {
      suppressWarnings(
        as.numeric(
          gene_ratios_mean_raw$R1_log2_TS_over_NTS
        )
      )
    } else {
      NA_real_
    },

    R2_log2_TS_over_NTS = if (
      "R2_log2_TS_over_NTS" %in%
        names(gene_ratios_mean_raw)
    ) {
      suppressWarnings(
        as.numeric(
          gene_ratios_mean_raw$R2_log2_TS_over_NTS
        )
      )
    } else {
      NA_real_
    },

    mean_log2_TS_over_NTS = suppressWarnings(
      as.numeric(
        mean_log2_TS_over_NTS
      )
    )
  ) %>%
  filter(
    !is.na(genotype),
    !is.na(timepoint),
    !is.na(quartile),
    !is.na(gene_match_id),
    gene_match_id != "",
    is.finite(
      mean_log2_TS_over_NTS
    )
  ) %>%
  arrange(
    timepoint,
    genotype,
    quartile,
    gene_match_id
  )

if (nrow(violin_plot_data) == 0) {
  stop(
    "No valid gene-level values remained for plotting."
  )
}

# ============================================================
# VERIFY ONE VALUE PER GENE AND CELL
# ============================================================

duplicate_gene_values <- violin_plot_data %>%
  count(
    genotype,
    timepoint,
    quartile,
    gene_match_id,
    name = "n_values"
  ) %>%
  filter(
    n_values != 1
  )

if (nrow(duplicate_gene_values) > 0) {
  print(
    duplicate_gene_values,
    n = Inf
  )

  stop(
    "Some genotype-timepoint-quartile-gene combinations ",
    "contain more than one replicate-mean value."
  )
}

# ============================================================
# GROUP COMPLETENESS QC
# ============================================================

plot_group_qc <- violin_plot_data %>%
  count(
    genotype,
    timepoint,
    quartile,
    name = "n_genes"
  ) %>%
  complete(
    genotype = factor(
      genotype_order,
      levels = genotype_order
    ),

    timepoint = factor(
      time_order,
      levels = time_order
    ),

    quartile = factor(
      quartile_order,
      levels = quartile_order
    ),

    fill = list(
      n_genes = 0L
    )
  ) %>%
  arrange(
    genotype,
    timepoint,
    quartile
  )

missing_groups <- plot_group_qc %>%
  filter(
    n_genes == 0
  )

if (nrow(missing_groups) > 0) {
  print(
    missing_groups,
    n = Inf
  )

  stop(
    "At least one genotype-timepoint-quartile group contains ",
    "no gene-level observations."
  )
}

message(
  "\nGenes represented in each violin:"
)

print(
  plot_group_qc,
  n = Inf
)

write_tsv(
  plot_group_qc %>%
    mutate(
      across(
        where(is.factor),
        as.character
      )
    ),
  file.path(
    outdir,
    "UVCPD_WT_CSB_DDB2_XPC_violin_group_QC.tsv"
  )
)

# ============================================================
# VERIFY IDENTICAL GENE SETS ACROSS GENOTYPES AND TIMEPOINTS
#
# Each quartile is assessed separately because quartiles
# naturally contain different genes.
# ============================================================

gene_set_qc <- violin_plot_data %>%
  group_by(
    quartile,
    genotype,
    timepoint
  ) %>%
  summarise(
    gene_set = list(
      sort(
        unique(
          gene_match_id
        )
      )
    ),

    n_genes = n_distinct(
      gene_match_id
    ),

    .groups = "drop"
  )

gene_set_comparison <- gene_set_qc %>%
  group_by(
    quartile
  ) %>%
  summarise(
    number_of_groups = n(),

    identical_gene_sets = {
      reference_set <- gene_set[[1]]

      all(
        map_lgl(
          gene_set,
          ~identical(
            .x,
            reference_set
          )
        )
      )
    },

    minimum_gene_number = min(
      n_genes
    ),

    maximum_gene_number = max(
      n_genes
    ),

    .groups = "drop"
  )

print(
  gene_set_comparison,
  n = Inf
)

write_tsv(
  gene_set_comparison %>%
    mutate(
      quartile = as.character(
        quartile
      )
    ),
  file.path(
    outdir,
    "UVCPD_WT_CSB_DDB2_XPC_violin_gene_set_QC.tsv"
  )
)

if (
  any(
    !gene_set_comparison$identical_gene_sets
  )
) {
  stop(
    "The plotted gene identities are not identical across ",
    "all genotypes and timepoints within at least one quartile."
  )
}

# ============================================================
# FULL SHARED SYMMETRIC Y-AXIS
#
# Uses the complete observed gene-level range.
# No observed values are excluded.
# ============================================================

observed_minimum <- min(
  violin_plot_data$mean_log2_TS_over_NTS,
  na.rm = TRUE
)

observed_maximum <- max(
  violin_plot_data$mean_log2_TS_over_NTS,
  na.rm = TRUE
)

observed_absolute_limit <- max(
  abs(
    c(
      observed_minimum,
      observed_maximum
    )
  ),
  na.rm = TRUE
)

if (
  !is.finite(observed_absolute_limit) ||
    observed_absolute_limit <= 0
) {
  stop(
    "Could not calculate a valid violin-plot y-axis."
  )
}

violin_absolute_limit <- (
  observed_absolute_limit *
    (
      1 +
        axis_padding_fraction
    )
)

# Round upward to the next 0.5.
violin_absolute_limit <- ceiling(
  violin_absolute_limit * 2
) / 2

violin_ymin <- -violin_absolute_limit
violin_ymax <- violin_absolute_limit

message(
  "\nObserved gene-level range: ",
  round(
    observed_minimum,
    4
  ),
  " to ",
  round(
    observed_maximum,
    4
  )
)

message(
  "Shared violin y-axis: ",
  violin_ymin,
  " to ",
  violin_ymax
)

# ============================================================
# VIOLIN SUMMARY
#
# Black vertical segment:
#   25th to 75th percentile
#
# White horizontal line:
#   median
# ============================================================

violin_summary <- violin_plot_data %>%
  group_by(
    genotype,
    timepoint,
    quartile
  ) %>%
  summarise(
    n_genes = n(),

    minimum_log2_TS_NTS = min(
      mean_log2_TS_over_NTS,
      na.rm = TRUE
    ),

    mean_log2_TS_NTS = mean(
      mean_log2_TS_over_NTS,
      na.rm = TRUE
    ),

    sd_log2_TS_NTS = sd(
      mean_log2_TS_over_NTS,
      na.rm = TRUE
    ),

    sem_log2_TS_NTS = (
      sd_log2_TS_NTS /
        sqrt(
          n_genes
        )
    ),

    q1_log2_TS_NTS = quantile(
      mean_log2_TS_over_NTS,
      probs = 0.25,
      na.rm = TRUE,
      names = FALSE
    ),

    median_log2_TS_NTS = median(
      mean_log2_TS_over_NTS,
      na.rm = TRUE
    ),

    q3_log2_TS_NTS = quantile(
      mean_log2_TS_over_NTS,
      probs = 0.75,
      na.rm = TRUE,
      names = FALSE
    ),

    maximum_log2_TS_NTS = max(
      mean_log2_TS_over_NTS,
      na.rm = TRUE
    ),

    fraction_TS_enriched = mean(
      mean_log2_TS_over_NTS > 0,
      na.rm = TRUE
    ),

    fraction_NTS_enriched = mean(
      mean_log2_TS_over_NTS < 0,
      na.rm = TRUE
    ),

    .groups = "drop"
  ) %>%
  mutate(
    genotype = factor(
      as.character(genotype),
      levels = genotype_order
    ),

    timepoint = factor(
      as.character(timepoint),
      levels = time_order
    ),

    quartile = factor(
      as.character(quartile),
      levels = quartile_order
    )
  ) %>%
  arrange(
    timepoint,
    genotype,
    quartile
  )

# ============================================================
# WRITE VIOLIN TABLES
# ============================================================

write_tsv(
  violin_plot_data %>%
    mutate(
      across(
        where(is.factor),
        as.character
      )
    ),
  file.path(
    outdir,
    "UVCPD_WT_CSB_DDB2_XPC_violin_gene_values.tsv"
  )
)

write_tsv(
  violin_summary %>%
    mutate(
      across(
        where(is.factor),
        as.character
      )
    ),
  file.path(
    outdir,
    "UVCPD_WT_CSB_DDB2_XPC_violin_summary.tsv"
  )
)

# ============================================================
# MAIN VIOLIN PLOT
#
# Rows:
#   0.5h
#   2h
#   4h
#   8h
#
# Columns:
#   WT
#   CSB
#   DDB2
#   XPC
#
# X-axis:
#   Q0-Q4
#
# Y-axis:
#   mean replicate log2(TS/NTS)
# ============================================================

violin_plot <- ggplot(
  violin_plot_data,
  aes(
    x = quartile,
    y = mean_log2_TS_over_NTS,
    fill = timepoint
  )
) +

  geom_hline(
    yintercept = 0,
    linetype = "dashed",
    color = "black",
    linewidth = 0.45
  ) +

  geom_violin(
    width = 0.88,
    scale = "width",
    trim = TRUE,
    adjust = density_adjust,
    color = "black",
    linewidth = 0.28,
    alpha = 0.84,
    na.rm = TRUE
  ) +

  # Interquartile range.
  geom_segment(
    data = violin_summary,
    aes(
      x = quartile,
      xend = quartile,
      y = q1_log2_TS_NTS,
      yend = q3_log2_TS_NTS
    ),
    inherit.aes = FALSE,
    linewidth = 1.5,
    color = "black",
    lineend = "round"
  ) +

  # Median.
  geom_crossbar(
    data = violin_summary,
    aes(
      x = quartile,
      y = median_log2_TS_NTS,
      ymin = median_log2_TS_NTS,
      ymax = median_log2_TS_NTS
    ),
    inherit.aes = FALSE,
    width = 0.34,
    linewidth = 0.65,
    color = "white"
  ) +

  facet_grid(
    rows = vars(
      timepoint
    ),

    cols = vars(
      genotype
    ),

    scales = "fixed",
    switch = "y"
  ) +

  scale_fill_manual(
    values = time_colors,
    breaks = time_order,
    drop = FALSE
  ) +

  scale_x_discrete(
    limits = quartile_order,
    drop = FALSE
  ) +

  scale_y_continuous(
    breaks = pretty(
      c(
        violin_ymin,
        violin_ymax
      ),
      n = 7
    ),

    expand = expansion(
      mult = c(
        0.02,
        0.02
      )
    )
  ) +

  coord_cartesian(
    ylim = c(
      violin_ymin,
      violin_ymax
    ),
    clip = "off"
  ) +

  labs(
    x = "Expression quartile",

    y = expression(
      mean ~ log[2] *
        frac(
          allTS + 0.5,
          allNTS + 0.5
        )
    ),

    title = "UV-CPD transcription-coupled repair",

    subtitle = paste0(
      "Gene-level R1/R2 mean log2(TS/NTS); ",
      "black segment = IQR, white line = median"
    )
  ) +

  guides(
    fill = "none"
  ) +

  theme_classic(
    base_size = 10
  ) +

  theme(
    axis.text.x = element_text(
      size = 8.2,
      color = "black"
    ),

    axis.text.y = element_text(
      size = 8.5,
      color = "black"
    ),

    axis.title.x = element_text(
      size = 10.5,
      margin = margin(
        t = 7
      )
    ),

    axis.title.y = element_text(
      size = 10.5,
      margin = margin(
        r = 7
      )
    ),

    axis.line = element_line(
      color = "black",
      linewidth = 0.35
    ),

    axis.ticks = element_line(
      color = "black",
      linewidth = 0.35
    ),

    panel.grid.major.y = element_line(
      color = "grey90",
      linewidth = 0.3
    ),

    panel.grid.major.x = element_blank(),

    panel.grid.minor = element_blank(),

    panel.border = element_rect(
      fill = NA,
      color = "grey60",
      linewidth = 0.35
    ),

    panel.spacing.x = grid::unit(
      0.50,
      "lines"
    ),

    panel.spacing.y = grid::unit(
      0.30,
      "lines"
    ),

    strip.background = element_rect(
      fill = "grey96",
      color = "grey60",
      linewidth = 0.35
    ),

    strip.text.x = element_text(
      face = "bold",
      size = 11,
      color = "black"
    ),

    strip.text.y.left = element_text(
      face = "bold",
      angle = 0,
      size = 9,
      color = "black"
    ),

    strip.placement = "outside",

    plot.title = element_text(
      hjust = 0.5,
      face = "bold",
      size = 13
    ),

    plot.subtitle = element_text(
      hjust = 0.5,
      size = 8.5
    ),

    plot.margin = margin(
      t = 8,
      r = 10,
      b = 8,
      l = 8
    )
  )

# ============================================================
# SAVE MAIN VIOLIN PLOT
# ============================================================

main_pdf_file <- file.path(
  outdir,
  "UVCPD_WT_CSB_DDB2_XPC_TS_NTS_quartile_violin_plots.pdf"
)

main_png_file <- file.path(
  outdir,
  "UVCPD_WT_CSB_DDB2_XPC_TS_NTS_quartile_violin_plots.png"
)

ggsave(
  filename = main_pdf_file,
  plot = violin_plot,
  width = 10.0,
  height = 8.3,
  units = "in",
  device = cairo_pdf
)

ggsave(
  filename = main_png_file,
  plot = violin_plot,
  width = 10.0,
  height = 8.3,
  units = "in",
  dpi = 600,
  bg = "white"
)

# ============================================================
# ONE FIGURE PER TIMEPOINT
#
# Columns:
#   WT, CSB, DDB2, XPC
#
# X-axis:
#   Q0-Q4
#
# The shared y-axis from the main figure is retained.
# ============================================================

save_one_timepoint_plot <- function(
  selected_timepoint
) {

  current_plot_data <- violin_plot_data %>%
    filter(
      as.character(timepoint) ==
        selected_timepoint
    )

  current_summary <- violin_summary %>%
    filter(
      as.character(timepoint) ==
        selected_timepoint
    )

  p_timepoint <- ggplot(
    current_plot_data,
    aes(
      x = quartile,
      y = mean_log2_TS_over_NTS,
      fill = timepoint
    )
  ) +

    geom_hline(
      yintercept = 0,
      linetype = "dashed",
      color = "black",
      linewidth = 0.45
    ) +

    geom_violin(
      width = 0.88,
      scale = "width",
      trim = TRUE,
      adjust = density_adjust,
      color = "black",
      linewidth = 0.28,
      alpha = 0.84,
      na.rm = TRUE
    ) +

    geom_segment(
      data = current_summary,
      aes(
        x = quartile,
        xend = quartile,
        y = q1_log2_TS_NTS,
        yend = q3_log2_TS_NTS
      ),
      inherit.aes = FALSE,
      linewidth = 1.5,
      color = "black",
      lineend = "round"
    ) +

    geom_crossbar(
      data = current_summary,
      aes(
        x = quartile,
        y = median_log2_TS_NTS,
        ymin = median_log2_TS_NTS,
        ymax = median_log2_TS_NTS
      ),
      inherit.aes = FALSE,
      width = 0.34,
      linewidth = 0.65,
      color = "white"
    ) +

    facet_grid(
      cols = vars(
        genotype
      )
    ) +

    scale_fill_manual(
      values = time_colors,
      breaks = time_order,
      drop = FALSE
    ) +

    scale_x_discrete(
      limits = quartile_order,
      drop = FALSE
    ) +

    scale_y_continuous(
      breaks = pretty(
        c(
          violin_ymin,
          violin_ymax
        ),
        n = 7
      ),

      expand = expansion(
        mult = c(
          0.02,
          0.02
        )
      )
    ) +

    coord_cartesian(
      ylim = c(
        violin_ymin,
        violin_ymax
      ),
      clip = "off"
    ) +

    labs(
      x = "Expression quartile",

      y = expression(
        mean ~ log[2] *
          frac(
            allTS + 0.5,
            allNTS + 0.5
          )
      ),

      title = paste0(
        "UV-CPD transcription-coupled repair — ",
        selected_timepoint
      ),

      subtitle = paste0(
        "Gene-level R1/R2 mean; ",
        "black segment = IQR, white line = median"
      )
    ) +

    guides(
      fill = "none"
    ) +

    theme_classic(
      base_size = 10
    ) +

    theme(
      axis.text.x = element_text(
        size = 8.5,
        color = "black"
      ),

      axis.text.y = element_text(
        size = 8.5,
        color = "black"
      ),

      axis.title = element_text(
        size = 10.5
      ),

      panel.grid.major.y = element_line(
        color = "grey90",
        linewidth = 0.3
      ),

      panel.grid.major.x = element_blank(),

      panel.grid.minor = element_blank(),

      panel.border = element_rect(
        fill = NA,
        color = "grey60",
        linewidth = 0.35
      ),

      panel.spacing.x = unit(
        0.50,
        "lines"
      ),

      strip.background = element_rect(
        fill = "grey96",
        color = "grey60",
        linewidth = 0.35
      ),

      strip.text = element_text(
        face = "bold",
        size = 11
      ),

      plot.title = element_text(
        hjust = 0.5,
        face = "bold",
        size = 13
      ),

      plot.subtitle = element_text(
        hjust = 0.5,
        size = 8.5
      )
    )

  safe_timepoint_name <- selected_timepoint %>%
    str_replace_all(
      "\\.",
      "p"
    )

  ggsave(
    filename = file.path(
      outdir,
      paste0(
        "UVCPD_WT_CSB_DDB2_XPC_",
        safe_timepoint_name,
        "_quartile_violin.pdf"
      )
    ),
    plot = p_timepoint,
    width = 10.0,
    height = 3.5,
    units = "in",
    device = cairo_pdf
  )

  ggsave(
    filename = file.path(
      outdir,
      paste0(
        "UVCPD_WT_CSB_DDB2_XPC_",
        safe_timepoint_name,
        "_quartile_violin.png"
      )
    ),
    plot = p_timepoint,
    width = 10.0,
    height = 3.5,
    units = "in",
    dpi = 600,
    bg = "white"
  )
}

walk(
  time_order,
  save_one_timepoint_plot
)

# ============================================================
# FINAL MESSAGES
# ============================================================

cat(
  "\nViolin plots completed.\n"
)

cat(
  glue(
    "Input table: {input_file}\n"
  )
)

cat(
  glue(
    "Genotypes: ",
    "{paste(genotype_order, collapse = ', ')}\n"
  )
)

cat(
  glue(
    "Observed gene-level range: ",
    "{round(observed_minimum, 4)} to ",
    "{round(observed_maximum, 4)}\n"
  )
)

cat(
  glue(
    "Shared y-axis: ",
    "{violin_ymin} to {violin_ymax}\n"
  )
)

cat(
  glue(
    "Output directory: {outdir}\n"
  )
)

cat(
  glue(
    "Main PDF: {main_pdf_file}\n"
  )
)

cat(
  glue(
    "Main PNG: {main_png_file}\n"
  )
)